
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ipd
 */
public class LibForm extends javax.swing.JFrame {

    /**
     * Creates new form LibForm
     */
    public LibForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_showbook = new javax.swing.JTable();
        btn_display = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_showuser = new javax.swing.JTable();
        btn_showuser = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_isbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_subject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_rackno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_barcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_publisher = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_family = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        btn_adduser = new javax.swing.JButton();
        btn_removeuser = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_showbook.setForeground(new java.awt.Color(0, 153, 153));
        tbl_showbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Subject", "Rack No", "ISBN", "Publisher", "Barcode", "UserID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_showbook);

        btn_display.setBackground(new java.awt.Color(0, 153, 153));
        btn_display.setForeground(new java.awt.Color(255, 255, 255));
        btn_display.setText("DISPLAY BOOKS");
        btn_display.setToolTipText("");
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });

        tbl_showuser.setForeground(new java.awt.Color(0, 153, 153));
        tbl_showuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Family", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_showuser);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_showuser.setBackground(new java.awt.Color(0, 153, 153));
        btn_showuser.setForeground(new java.awt.Color(255, 255, 255));
        btn_showuser.setText("SHOW MEMBER");
        btn_showuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_showuser)
                            .addComponent(btn_display))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_display)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_showuser))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Title");

        txt_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_titleActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rack No");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ISBN");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Publisher");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Barcode");

        btn_search.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 51, 51));
        btn_search.setText("SEARCH");
        btn_search.setToolTipText("Search by Ttile");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        btn_remove.setForeground(new java.awt.Color(0, 51, 51));
        btn_remove.setText("REMOVE");
        btn_remove.setToolTipText("Remove By Title");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(0, 51, 51));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_add.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 51, 51));
        btn_add.setText("ADD");
        btn_add.setToolTipText("Add a Book");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Member Name");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Family");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Age");

        btn_adduser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 11)); // NOI18N
        btn_adduser.setForeground(new java.awt.Color(0, 51, 51));
        btn_adduser.setText("ADD");
        btn_adduser.setToolTipText("Add a Member");
        btn_adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adduserActionPerformed(evt);
            }
        });

        btn_removeuser.setBackground(new java.awt.Color(255, 255, 255));
        btn_removeuser.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 11)); // NOI18N
        btn_removeuser.setForeground(new java.awt.Color(0, 51, 51));
        btn_removeuser.setText("REMOVE");
        btn_removeuser.setToolTipText("Remove By Name");
        btn_removeuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeuserActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("UserID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_rackno, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_name)
                                    .addComponent(txt_family)
                                    .addComponent(txt_age, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_removeuser)
                                .addGap(8, 8, 8)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rackno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_search)
                    .addComponent(btn_remove))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_family, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_removeuser)
                    .addComponent(btn_adduser))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_back.setForeground(new java.awt.Color(0, 153, 153));
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_back)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_back)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
           try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="insert into book(title,subject,rackNo,ISBN,publisher,bookBarCode,userid) values('%s', '%s', '%s', '%s', '%s', '%s', '%s')";
                query=String.format(query, txt_title.getText(), txt_subject.getText(), txt_rackno.getText(), txt_isbn.getText(), txt_publisher.getText(), txt_barcode.getText(), txt_userid.getText());
                state.execute(query);
                state.close();
                connect.close();
                txt_rackno.setText("");
                txt_title.setText("");
                txt_subject.setText("");
                txt_isbn.setText("");
                txt_publisher.setText("");
                txt_barcode.setText("");
                txt_userid.setText("");
                showTableData();
                
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adduserActionPerformed
        // TODO add your handling code here:
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="insert into user(username, family, age) values('%s', '%s', '%s')";
                query=String.format(query, txt_name.getText(), txt_family.getText(), txt_age.getText());
                state.execute(query);
                state.close();
                connect.close();
                txt_name.setText("");
                txt_family.setText("");
                txt_age.setText("");
                showUserData();
                
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btn_adduserActionPerformed

    private void btn_removeuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeuserActionPerformed
        // TODO add your handling code here:
         try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="delete from user where username='%s'";
                query=String.format(query, txt_name.getText());
                state.execute(query);
                state.close();
                connect.close();
                txt_name.setText("");
                showUserData();
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btn_removeuserActionPerformed

    private void btn_showuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showuserActionPerformed
        showUserData();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_showuserActionPerformed

    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
        showTableData();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_displayActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="update book set title='%s', subject='%s',rackNo='%s',ISBN='%s',publisher='%s',bookBarcode='%s',userid='%s' where title='%s'";
                query=String.format(query, txt_title.getText(),txt_subject.getText(),txt_rackno.getText(),txt_isbn.getText(),txt_publisher.getText(),txt_barcode.getText(),txt_userid.getText(),txt_title.getText());
                state.execute(query);
                state.close();
                connect.close();
                txt_rackno.setText("");
                txt_title.setText("");
                txt_subject.setText("");
                txt_isbn.setText("");
                txt_publisher.setText("");
                txt_barcode.setText("");
                txt_userid.setText("");
                showTableData();
            }     
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="select * from book where title='%s'";
                query=String.format(query, txt_title.getText());
                state.execute(query);
                
                ResultSet result=state.executeQuery(query);
                ClearBookTable();
                    while(result.next()){
                        
                        String title=result.getString(2);
                        String subject=result.getString(3);
                        String rackNo=result.getString(4);
                        String isbn=result.getString(5);
                        String publisher=result.getString(6);
                        String barcode=result.getString(7);
                        String userid=result.getString(8);
                        Object[] content={title,subject,rackNo,isbn,publisher,barcode,userid};
                        DefaultTableModel model= (DefaultTableModel) tbl_showbook.getModel();
                        model.addRow(content);
                    }
                    
                state.close();
                connect.close();
                txt_rackno.setText("");
                txt_title.setText("");
                txt_subject.setText("");
                txt_isbn.setText("");
                txt_publisher.setText("");
                txt_barcode.setText("");
                //showTableData();
                
            }     
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javalibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="delete from book where title='%s'";
                query=String.format(query, txt_title.getText());
                state.execute(query);
                state.close();
                connect.close();
                txt_title.setText("");
                showTableData();
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_titleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibForm().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_adduser;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_display;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_removeuser;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_showuser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_showbook;
    private javax.swing.JTable tbl_showuser;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_barcode;
    private javax.swing.JTextField txt_family;
    private javax.swing.JTextField txt_isbn;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_publisher;
    private javax.swing.JTextField txt_rackno;
    private javax.swing.JTextField txt_subject;
    private javax.swing.JTextField txt_title;
    private javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables

    private void showTableData() {
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javaLibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="select * from book";
                ResultSet result=state.executeQuery(query);
                ClearBookTable();
                    while(result.next()){
                        
                        String title=result.getString(2);
                        String subject=result.getString(3);
                        String rackNo=result.getString(4);
                        String isbn=result.getString(5);
                        String publisher=result.getString(6);
                        String barcode=result.getString(7);
                        String userid=result.getString(8);
                        Object[] content={title,subject,rackNo,isbn,publisher,barcode,userid};
                        DefaultTableModel model= (DefaultTableModel) tbl_showbook.getModel();
                        model.addRow(content);
                    }
                state.close();
                connect.close();
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }

    private void showUserData() {
        try{
                Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
                String url="jdbc:mysql://localhost:3306/javaLibrary?user=root";
                Connection connect=DriverManager.getConnection(url);
                Statement state=connect.createStatement();
                String query="select * from user";
                ResultSet result=state.executeQuery(query);
                ClearUserTable();
                    while(result.next()){
                        String name=result.getString(1);
                        String family=result.getString(2);
                        String age=result.getString(3);
                        Object[] content={name,family,age};
                        DefaultTableModel model= (DefaultTableModel) tbl_showuser.getModel();
                        model.addRow(content);
                    }
                state.close();
                connect.close();
            }
            catch(IllegalAccessException | InstantiationException | ClassNotFoundException | SQLException e){
                e.printStackTrace();
            }
    }
        public void ClearBookTable(){
            DefaultTableModel dm= (DefaultTableModel) tbl_showbook.getModel();
                int rowCount = dm.getRowCount();
                    for(int i= rowCount-1;i>=0;i--){
                        dm.removeRow(i);
                    }
        }
        public void ClearUserTable(){
            DefaultTableModel dm= (DefaultTableModel) tbl_showuser.getModel();
                int rowCount = dm.getRowCount();
                    for(int i= rowCount-1;i>=0;i--){
                        dm.removeRow(i);
                    }
        }
}
